// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShelterAPI.Models;

#nullable disable

namespace PetShelterAPI.Migrations
{
    [DbContext(typeof(PetShelterAPIContext))]
    partial class PetShelterAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetShelterAPI.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("PetId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            Age = 7,
                            Color = "brown",
                            Description = "est. Nunc laoreet lectus quis massa. Mauris vestibulum,",
                            Name = "Matilda",
                            Sex = "Female",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 2,
                            Age = 2,
                            Color = "black",
                            Description = "pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec",
                            Name = "Rexie",
                            Sex = "Female",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 3,
                            Age = 4,
                            Color = "white",
                            Description = "tincidunt tempus risus. Donec egestas. Duis ac arcu.",
                            Name = "Matilda",
                            Sex = "Male",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 4,
                            Age = 4,
                            Color = "white",
                            Description = "enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida",
                            Name = "Pip",
                            Sex = "Female",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 5,
                            Age = 1,
                            Color = "cream",
                            Description = "ultrices posuere cubilia Curae Phasellus ornare.",
                            Name = "Bartholomew",
                            Sex = "Male",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
